force-app/main/default/objects/Error_Log__c/fields/Error_message__c.field-meta.xml
<CustomField>
    <fullName>Error_message__c</fullName>
    <label>Error message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ErrorLogger.cls
/**
 * @Description: Apex class for creating Error logs
 * @Author: Rohit
 * @Class Name: ErrorLogger
 */

public with sharing class ErrorLogger {

    /**
     * Desciption: Method to create error logs
     * Param: Class Name and Error message
     * Return values: Error_Log__c
     */
    public STATIC Error_Log__c createErrorLog(String className, String errorMessage) {
        Error_Log__c errorLog = new Error_Log__c();
        errorLog.Class_Name__c = className;
        errorLog.Error_message__c = errorMessage;
        errorLog.User_Name__c = UserInfo.getUserId();
        return errorLog;
    }
}